// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbQTVfzE7A6Xo_exagQZU1taRgk9nFVI',
    appId: '1:961241936685:android:faf395ac4319e5178459a4',
    messagingSenderId: '961241936685',
    projectId: 'andrehouse-e8abe',
    databaseURL: 'https://andrehouse-e8abe-default-rtdb.firebaseio.com',
    storageBucket: 'andrehouse-e8abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhfhgo2k-kbOxbfPbqLN8VkGF_sr__Ro',
    appId: '1:961241936685:ios:8ec2f5f2d4d6184b8459a4',
    messagingSenderId: '961241936685',
    projectId: 'andrehouse-e8abe',
    databaseURL: 'https://andrehouse-e8abe-default-rtdb.firebaseio.com',
    storageBucket: 'andrehouse-e8abe.appspot.com',
    iosClientId: '961241936685-pg7rt28e5v4o8s26nmfsttmecr1k00l3.apps.googleusercontent.com',
    iosBundleId: 'come.example.AndreHouse',
  );
}
